[package]
name = "nrobloxs/basicsignal"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A lightweight, GoodSignal-style event/signal implementation for Roblox with thread pooling."

[dependencies]
